### ISSUE TITLE
Create a new connector component that encapsulates APM-related signaltometrics config

### ISSUE THREAD

**Issue by axw** [elastic/opentelemetry-collector-components#336]
We should create a new connector that encapsulates this config: https://github.com/elastic/opentelemetry/blob/ccb569542dc3a381461dca58769f8c1d2149c474/resources/kubernetes/operator/helm/values.yaml#L259-L492

This will avoid users having to copy & paste the config, and encounter drift. We may provide some extension points in the config, e.g. to add more resource/signal attributes to include in aggregations.

**Comment by lahsivjar** [comment]
I have discussed this with @simitt a bit and I think that while encapsulating complexity would be a good idea, we should also think about what we want to expose to the users as configuration. Wrapping configuration in a component would get quite involved based on what we expect from the customers to modify, for example, if we want the customer to be able to modify existing resource attributes used for generating transaction metrics then we would have to build a configuration to modify the existing configuration. OTOH, if we want the users to be able to add new signal to metrics configuration then we would want to expose the configuration offered by the signal to metrics component.

Basically, my point here is that abstracting complexity in itself sounds good but based on what knobs we want to offer to the customer for customizing the config this might get into the territory of more involved accidental complexity and defeat our purpose of a simpler interface for getting started.

**Comment by axw** [comment]
@lahsivjar fair points. How would you suggest we proceed? I had in mind that we would start with a component that encapsulates the configuration, and provides no configuration settings at all. Then we would add configuration after we know more about what needs to be configurable.

**Comment by lahsivjar** [comment]
If we want to start with no configuration then should we just have some form of templating to download the configuration files from somewhere while building the collector rather than wrapping it into a single component? - I am not against the component but just wondering if we should do it when we have the requirements of what we would want to expose to the customers a bit more clearer.

**Comment by lahsivjar** [comment]
@axw and I talked on zoom and I am good with starting with a zero configuration component wrapper wrapping the signal to metrics connector.

**Comment by felixbarny** [comment]
Generally, the component should offer a similar layer of abstraction for configuration as APM Server. The fact that this is using signaltometrics, batch, and lsminterval under the hood should be an implementation detail.

**Comment by lahsivjar** [comment]
@felixbarny Do you mean we should wrap the whole pipeline for apm aggregations? While I love the idea, I am not sure if we can wrap more than one component in another component.

**Comment by lahsivjar** [comment]
Hmm, maybe we can create a connector that could wrap the signaltometrics connector and lsminterval processor together... I can work on this if it is free to pick (I have a couple days before my PTO and I think that should be enough to get a working version).

**Comment by felixbarny** [comment]
> @felixbarny Do you mean we should wrap the whole pipeline for apm aggregations? 
> Hmm, maybe we can create a connector that could wrap the signaltometrics connector and lsminterval processor together in a new connector... 

Yes, that's exactly what I mean. As a connector can also do processing, we should be able to combine processors and connectors into a single connector component.

**Comment by axw** [comment]
Vishal was going to pick it up but uncovered some performance issues in lsmintervalprocessor before PTO, assigning to myself now.

**Comment by axw** [comment]
I'm also considering adding `elastictraceprocessor` into the component, so we can just point an OTLP receiver at it and have it do all the Elastic APM things. This does complicate the implementation, as I'll describe below, but I think would simplify configuration for users.

We have a couple of options: either a monolithic connector, or a monolithic processor. Both have downsides, but I think going with a processor may be the least-worst option.

If we go with a connector, then it seems fairly natural at first: we would need to implement `traces_to_metrics`, `logs_to_metrics`, `metrics_to_metrics` -- this is what `signaltometrics` does. We also want the input signals to go to another consumer (e.g. the ES exporter). That is straightforward when `elastictraceprocessor` is outside the component, but if we need to process within then we would also need the connector to do `traces_to_traces` and `logs_to_logs`, so we can do the processing and send to the next thing. There are two more complications: with a connector like this we would need to receive not just metrics from the connector, but logs and traces too, which complicates the user config; and we would need to perform enrichment twice each traces -- once for `traces_to_metrics`, and once for `traces_to_traces`. In the end, the config would look something like this:

```yaml
connectors:
  elasticapm:
    aggregation:
      directory: /path/to/lsm/storage

receivers:
  otlp: ...

exporters:
  elasticsearch: ...

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [elasticapm]
    metrics:
      receivers: [otlp]
      exporters: [elasticapm]
    traces:
      receivers: [otlp]
      exporters: [elasticapm]

    logs/elasticapm:
      receivers: [elasticapm]
      exporters: [elasticsearch]
    metrics/elasticapm:
      receivers: [elasticapm]
      exporters: [elasticsearch]
    traces/elasticapm:
      receivers: [elasticapm]
      exporters: [elasticsearch]
```

If we go with a processor, things are a bit better: the processor would be capable of processing logs, metrics, and traces. We would use the next metrics consumer as the output of the embedded lsminterval processor. If the processor is not used in a metrics pipeline then there would be no aggregation; it would be an error to use it in more than one metrics pipeline, since then we wouldn't know where to send the metrics. This feels a bit hacky, but simplifies the configuration to:

```yaml
processors:
  elasticapm:
    aggregation:
      directory: /path/to/lsm/storage

receivers:
  otlp: ...

exporters:
  elasticsearch: ...

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [elasticapm]
      exporters: [elasticsearch]
    metrics:
      receivers: [otlp]
      processors: [elasticapm]
      exporters: [elasticsearch]
    traces:
      receivers: [otlp]
      processors: [elasticapm]
      exporters: [elasticsearch]
```

Alternatively we concede and keep any other processing out of the component, making it only about signaltometrics/lsminterval.
