### ISSUE TITLE
IntakeV2 receiver configuration issues

### ISSUE THREAD

**Issue by gregkalapos** [elastic/opentelemetry-collector-components#514]
The intakeV2 receiver can be configured the following way:

```
service:
  extensions: [basicauth]
  pipelines:
    traces/otel-apm:
      receivers: [elasticapm/intake]
      exporters: [elasticsearch]
```

So far so good - `elasticapm/intake` starts listening on an HTTP port and receive all the ndjoson data that APM Server receives.

However, one we want to create logs as well, then this setup doesn't work because remains `nil` because the [`nextLogs` `consumer.Logs`](https://github.com/elastic/opentelemetry-collector-components/blob/main/receiver/elasticapmreceiver/receiver.go#L68C2-L68C27) won't be initialized by the collector.

From what I understand that is because there is no logs pipeline created in the above setup. The result is, that as soon as we want to create a `logRecord` (e.g. for an error), we can't do that. 

Same applies for metrics.

One option to fix it with the current code-base is to add a logging pipeline with the same config:

```
service:
  extensions: [basicauth]
  pipelines:
    logs/otel-apm:
      receivers: [elasticapm/intake]
      exporters: [elasticsearch]
    traces/otel-apm:
      receivers: [elasticapm/intake]
      exporters: [elasticsearch]
```

This solves the problem, but these two pipelines are basically the same. Also for an Elastic APM user it can be a bit confusing that they expect a single HTTP endpoint to send data to, but here they need to configure 2 (with metrics 3) pipelines.

Question: 
- Is there a better solution for this?
- Do we want to improve this?

Even if this remains this way, I'll document this, because it is potentially confusing.
